[pytest]

testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -ra
    --strict-config
    --strict-markers

markers =
    smoke: критические smoke-тесты
    regression: регрессионные тесты
    users: тесты пользователя
    products: тесты продукта
    auth: тесты авторизации
    orders: тесты заказа
